#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
blacklist = ["scratchpad"]

cache = false

sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
dir_length = 3

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "workspaces 🏗️"
path = "~/Workspaces"

[[session]]
name = "Obsidian 🗒 ️"
path = "~/Obsidian"
startup_command = "nvim ."

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "dotfiles 💻"
path = "~/dotfiles"
windows = [
  "tmuxconfig",
  "wezterm config",
  "neovim config",
  "aerospace config",
  "dot-ai",
]

[[session]]
name = "dot-ai 🤖"
path = "~/Workspaces/leovanhaaren/dot-ai"
startup_command = "nvim ."

[[session]]
name = "pi4 🖥️"
path = "~/Workspaces/leovanhaaren/pi4"
windows = ["pi4"]

[[session]]
name = "CSW"
path = "~/Workspaces/ksyos/ClientSafeWeb"
windows = ["wt list", "pi4", "gh dash", "lazygit"]

[[session]]
name = "CSW validation 🧪"
path = "~/Workspaces/ksyos/csw-e2e-validation"
windows = ["validation control"]

[[session]]
name = "sidekick 🦾"
path = "~/Workspaces/leo-ksyos/sidekick"
windows = ["wt list", "pi4", "gh dash", "lazygit"]

[[session]]
name = "automation ⚙️"
path = "~/Workspaces/leo-ksyos/sidekick"
startup_command = "just scheduled-prompts"

# General related sessions

[[window]]
name = "tmuxconfig"
path = "~/dotfiles"
startup_script = "nvim .tmux.conf"

[[window]]
name = "wezterm config"
path = "~/dotfiles/.config/wezterm"
startup_script = "nvim wezterm.lua"

[[window]]
name = "neovim config"
path = "~/dotfiles/.config/nvim"

[[window]]
name = "aerospace config"
path = "~/dotfiles/.config/aerospace"
startup_script = "nvim aerospace.toml"

[[window]]
name = "dot-ai"
path = "~/Workspaces/leovanhaaren/dot-ai"
startup_script = "nvim ."

[[window]]
name = "pi4"
startup_script = "zsh -lc 'source ~/.functions; pi4_here'"

# Work related windows

[[window]]
name = "wt list"
startup_script = "wt list"

[[window]]
name = "validation control"
path = "~/Workspaces/ksyos/csw-e2e-validation"
startup_script = "just session; just status"

[[window]]
name = "gh dash"
startup_script = "gh dash"

[[window]]
name = "lazygit"
startup_script = "lazygit"
