#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
blacklist = ["scratchpad"]

cache = false

sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
dir_length = 3

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "second brain"
path = "~/c/second-brain"
startup_command = "nvim +ObsidianToday"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "tmuxconfig"
path = "~/dotfiles/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/tmux.conf"

[[session]]
name = "wezterm config"
path = "~/dotfiles/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "neovim config"
path = "~/dotfiles/.config/nvim"

[[session]]
name = "aerospace config"
path = "~/dotfiles/.config/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --language=bash --style=snip --color=always ~/dotfiles/.config/aerospace/aerospace.toml"

[[session]]
name = "dot-ai"
path = "~/Workspaces/leovanhaaren/dot-ai"
startup_command = "nvim ."

