tmux:
    symbols:
        branch: '⎇ '
        hashprefix: ':'
        ahead: ↑·
        behind: ↓·
        staged: '● '
        conflict: '✖ '
        modified: '✚ '
        untracked: '… '
        stashed: '⚑ '
        clean: ✔
        insertions: Σ
        deletions: Δ
    styles:
        clear: "#[fg=#{@thm_fg}]"
        state: "#[fg=#{@thm_red}]"
        branch: "#[fg=#{@thm_fg}]"
        remote: "#[fg=#{@thm_teal}]"
        divergence: "#[fg=#{@thm_fg}]"
        staged: "#[fg=#{@thm_green}]"
        conflict: "#[fg=#{@thm_red}]"
        modified: "#[fg=#{@thm_yellow}]"
        untracked: "#[fg=#{@thm_mauve}]"
        stashed: "#[fg=#{@thm_blue}]"
        clean: "#[fg=#{@thm_rosewater}]"
        insertions: "#[fg=#{@thm_green}]"
        deletions: "#[fg=#{@thm_red}]"
    layout: [branch, .., remote-branch, divergence, '- ', flags]
    options:
        branch_max_len: 0
        branch_trim: right
        ellipsis: …
        hide_clean: false
        swap_divergence: false
        divergence_space: false