#!/bin/bash
set -e

dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
current_dir="$(pwd -P)"

if [ "$current_dir" = "$dotfiles_dir" ]; then
  if command -v code >/dev/null 2>&1; then
    "$dotfiles_dir/bin/save-vscode-extensions"
    git add vscode/extensions.list
  fi

  git add vscode/settings.json
fi
